---
layout: post
title: 예외처리
categories: Java
tags: [Java]
---

● throw

 - 예외를 만들 때 사용. 예외를 처리하는 throws와 다름.

```java
public class ThrowEx {

	public static void main(String[] args) {
		try {
		    Exception e = new Exception("고의로 발생");
		    throw e;				// = throw new Exception("고의로 발생");
		} catch (Exception e) {
		    e.printStackTrace();
		    String reason = e.getMessage();
		    System.out.println(reason);
		}
	}

}
```

```
> java.lang.Exception: 고의로 발생
  	at ch08.ThrowEx.main(asdf.java:7)
  고의로 발생
```

● throws

 - try-catch문 처럼 예외를 처리할 때 사용.

 - 메서드의 선언부에 작성하는데 여러개를 던질 수 있음.(작은 범위 -> 큰범위 순으로 작성)

● RuntimeException

 - RuntimeException 처리는 강제가 아니기 때문에 Exception처리를 안해도 됨.

 - throws로 예외처리를 해줄 때 RuntimeException 하나만 딱 사용하면 모든 예외처리 가능.

---
Try-Catch 문을 사용할 때 Catch문을 여러개 사용할 경우, 하위에 해당하는 Exception부터 처리해야함.

ex ) ArithmeticException -> RuntimeException -> Exception 순으로

```java
public class ExceptionEx1 {

	public static void main(String[] args) {
		try {
		    System.out.println(1/0);
		} catch (ArithmeticException e) {		//ArithmeticException만 실행
		    System.out.println("0으로 나누지 마세요");
        	  e.printStackTrace();
		} catch (RuntimeException e) {			//RuntimeException중 ArithmeticException이 아닌것만 실행
		    System.out.println("연락요망");
		    e.printStackTrace();	
		} catch (Exception e) {				 //RuntimeException 이외의 나머지 Exception이 실행		
       		    e.printStackTrace();
        }
    }

}

```

try문을 실행하다가 예외가 발생했을 때 여러개의 catch문이 존재한다면 위에서부터 instanceof의 결과가 true인 catch문을 찾아내려간다. 찾으면 그 catch문 하나만을 실행하고 try-catch문을 빠져나온다.

● return시 순서

```java
public class ExceptionEx3 {

	public static void main(String[] args) {
		try {
			System.out.print(1);
			System.out.print(2);
			System.out.print(3/0);		// exception 발생
			System.out.print(4);
		} catch (Exception e) {
			System.out.print(5);
			return;				 //main method 종료
		} finally {
			System.out.print(6);
		}
		System.out.print(7);
	}	

}

```

```java
> 1256
```